[package]
name = "cadenza-infra-synth-rustysynth"
version = "0.1.0"
edition = "2021"

[dependencies]
cadenza-ports = { path = "../cadenza-ports" }
cadenza-infra-synth-waveguide-piano = { path = "../cadenza-infra-synth-waveguide-piano" }
parking_lot = "0.12"
rustysynth = "1"
