[package]
name = "cadenza-domain-score"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
midly = "0.5"

cadenza-ports = { path = "../cadenza-ports" }
